# Generated by Django 5.1.7 on 2025-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
